pipeline {
    agent any
 //   environment {
   //     s3_bucket = "persistent-demo1"
     //           }
    parameters { string(name: 'S3_BUCKET', defaultValue: 'persistent-demo1', description: 'This bucket is use to store the stage files')
                 string(name: 'KUBERNET_CLUSTER_NAME', defaultValue: 'persistent-k8s-demo.k8s.local', description: 'Kubernet Cluster Name, 1 - master & 2 nodes')
                 choice(name: 'CHOICE', choices: ['Create', 'Destory'], description: 'Pick your Choice')
               }
    
    stages{
        stage ('Create S3 Bucket') {
            steps {
                sh "aws s3api create-bucket --bucket ${params.S3_BUCKET} --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1"
                  }
             }
        stage('Create Kubernet Cluster') {
            // agent any
            steps {
                sh "export KOPS_STATE_STORE=s3://${params.S3_BUCKET}"
           //     sh "kops create cluster ${params.KUBERNET_CLUSTER_NAME} --zones ap-south-1a --yes"
            }
        }
    }
 }
