pipeline {
    agent any
 //   environment {
   //     s3_bucket = "persistent-demo1"
     //           }
    parameters { string(name: 'S3 Bucket Name', defaultValue: 'persistent-demo1', description: '') }
    
    stages{
        stage ('Create S3 Bucket') {
            steps {
                sh 'aws s3api create-bucket --bucket ${{params.s3_bucket} --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1'
                  }
             }
        stage('Create Kubernet Cluster') {
            // agent any
            steps {
                sh 'export KOPS_STATE_STORE=s3://${{params.s3_bucket}'
          //    sh 'kops create cluster persistent-k8s-demo.k8s.local --zones ap-south-1a --yes'
            }
        }
    }
 }
