pipeline {
    agent any
    parameters { 
                 choice(name: 'DEPLOYMENT_CHOICE', choices: ['Create', 'Destory'], description: 'Pick your Choice')
               }
        stages {
            stage ('Deploy/Destory Elastic Search and Service') {
               steps { 
                   script{
                    if ( params.DEPLOYMENT_CHOICE == 'Create')
                        {
                        sh 'kubectl create -f elasticsearch_kibana_fluend/elasticsearch_deployment.yaml'
                        sh 'kubectl create -f elasticsearch_kibana_fluend/elasticsearch_service.yaml'
                        }
                    else
                        {
			sh 'kubectl delete -f elasticsearch_kibana_fluend/elasticsearch_deployment.yaml'
                        sh 'kubectl delete -f elasticsearch_kibana_fluend/elasticsearch_service.yaml'
                         }
		      }
		   }
	       }
	     stage ('Deploy/Destory Kiban and Service') {
               steps { 
                   script{
                    if ( params.DEPLOYMENT_CHOICE == 'Create')
                        {
                        sh 'kubectl create -f elasticsearch_kibana_fluend/kibana_deployment.yaml'
                        sh 'kubectl create -f elasticsearch_kibana_fluend/kibana_svc.yaml'
                        }
                    else
                        {
			sh 'kubectl delete -f elasticsearch_kibana_fluend/kibana_deployment.yaml'
                        sh 'kubectl delete -f elasticsearch_kibana_fluend/kibana_svc.yaml'
                         }
		      }
		   }
	       }
		stage ('Deploy/Destory Fluend as DaemonSet') {
               steps { 
                   script{
                    if ( params.DEPLOYMENT_CHOICE == 'Create')
                        {
                        sh 'kubectl create -f elasticsearch_kibana_fluend/fluend.yaml'
                       
                        }
                    else
                        {
			 sh 'kubectl delete -f elasticsearch_kibana_fluend/fluend.yaml'
                     }
		   }
	        }
		}
		stage ('Deploy/Destory metricbeat as DaemonSet') {
               steps { 
                   script{
                    if ( params.DEPLOYMENT_CHOICE == 'Create')
                        {
                        sh 'kubectl create -f elasticsearch_kibana_fluend/metricbeat-kubernetes.yaml'
                       
                        }
                    else
                        {
			 sh 'kubectl delete -f elasticsearch_kibana_fluend/metricbeat-kubernetes.yaml'
                     }
		   }
	        }
		}
 	   }   
	 }
	
		            

		            
