apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ruby-mysql
  labels:
    app: ruby-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-mysql
  template:
    metadata:
      labels:
        app: ruby-mysql
    spec:
      containers:
      - name: mysql
        image: vikramsardeshpande/development-mysql:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
